[package]
name = "project-euler"
version = "0.1.0"
edition = "2021"

[lib]
name = "project_euler"

[[bin]]
name = "project-euler"
path = "bin/main.rs"

[dependencies]
rstest = { version = "0.17.0", default-features = false }
